@baseURL = http://localhost:3000
@userId = 1

### Get all users
GET {{baseURL}}/api/users

### 
GET {{baseURL}}

### Get user by ID
GET {{baseURL}}/api/users/{{userId}}
### Create a new user
POST {{baseURL}}/api/users/
Content-Type: application/json

{
  "name": "ranik20",
  "email": "ranik200@example.com",
  "password": "securepassword",
  "age": 40
} 


### Update a user
PUT {{baseURL}}/api/users/{{userId}}
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
}

### Delete a user
DELETE {{baseURL}}/api/users/6a2337cf9aa21ebebd767f33