@baseURL = http://localhost:3000
@userId = 1

### Get all users
GET {{baseURL}}/api/users

### Get user by ID
GET {{baseURL}}/api/users/{{userId}}
### Create a new user
POST {{baseURL}}/api/users/
Content-Type: application/json

{
  "name": "rani",
  "email": "ranik20@example.com",
  "password": "securepassword",
  "age": 30
} 


### Update a user
PUT {{baseURL}}/api/users/{{userId}}
Content-Type: application/json

{
  "name": "Jane Doe",
  "email": "jane.doe@example.com",
}

### Delete a user
DELETE {{baseURL}}/api/users/{{userId}} 